apps/comments/urls.py
from django.urls import path

from . import views

app_name = "comments"
urlpatterns = [
    path(
        'article/<int:article_id>/postcomment',
        views.CommentPostView.as_view(),
        name='postcomment',
    ),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = "blog"
urlpatterns = [
    path(
        r'',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
    path(
        r'clean',
        views.clean_cache_view,
        name='clean'),
    path(
        r'compare-versions',
        views.compare_versions,
        name='compare_versions'),
]

comments/urls.py
from django.urls import path

from . import views

app_name = "comments"
urlpatterns = [
    path(
        'article/<int:article_id>/postcomment',
        views.CommentPostView.as_view(),
        name='postcomment'),
    path(
        'comment/<int:comment_id>/react',
        views.CommentReactionView.as_view(),
        name='comment_react'),
]

djangoblog/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.urls import re_path
from haystack.views import search_view_factory
from django.http import JsonResponse
import time

from blog.views import EsSearchView
from djangoblog.admin_site import admin_site
from djangoblog.elasticsearch_backend import ElasticSearchModelSearchForm
from djangoblog.feeds import DjangoBlogFeed
from djangoblog.sitemap import ArticleSiteMap, CategorySiteMap, StaticViewSitemap, TagSiteMap, UserSiteMap

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'


def health_check(request):
    """
    健康检查接口
    简单返回服务健康状态
    """
    return JsonResponse({
        'status': 'healthy',
        'timestamp': time.time()
    })

from servermanager.views import statistics_view

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('health/', health_check, name='health_check'),
    path('statistics/', statistics_view, name='statistics'),
    path('servermanager/', include('servermanager.urls', namespace='servermanager')),
]
urlpatterns += i18n_patterns(
    re_path(r'^admin/', admin_site.urls),
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^feed/$', DjangoBlogFeed()),
    re_path(r'^rss/$', DjangoBlogFeed()),
    re_path('^search', search_view_factory(view_class=EsSearchView, form_class=ElasticSearchModelSearchForm),
            name='search'),
    path('servermanager/', include('servermanager.urls', namespace='servermanager')),
    re_path(r'', include('owntracks.urls', namespace='owntracks')),
    re_path(r'', include('blog.urls', namespace='blog')),
    re_path(r'', include('comments.urls', namespace='comment')),
    re_path(r'', include('accounts.urls', namespace='account')),
    re_path(r'', include('oauth.urls', namespace='oauth'))
    , prefix_default_language=False) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/comments/models.py
from django.conf import settings
from django.db import models
from django.utils.timezone import now

from blog.models import Article


# Create your models here.


class Comment(models.Model):
    body = models.TextField('正文', max_length=300)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='作者', on_delete=models.CASCADE
    )
    article = models.ForeignKey(Article, verbose_name='文章', on_delete=models.CASCADE)
    parent_comment = models.ForeignKey(
        'self', verbose_name="上级评论", blank=True, null=True, on_delete=models.CASCADE
    )
    is_enable = models.BooleanField('是否显示', default=True, blank=False, null=False)

    class Meta:
        ordering = ['-id']
        verbose_name = "评论"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def __str__(self):
        return self.body

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

comments/models.py
from django.conf import settings
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _

from blog.models import Article


# Create your models here.

class Comment(models.Model):
    body = models.TextField('正文', max_length=300)
    creation_time = models.DateTimeField(_('creation time'), default=now)
    last_modify_time = models.DateTimeField(_('last modify time'), default=now)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('author'),
        on_delete=models.CASCADE)
    article = models.ForeignKey(
        Article,
        verbose_name=_('article'),
        on_delete=models.CASCADE)
    parent_comment = models.ForeignKey(
        'self',
        verbose_name=_('parent comment'),
        blank=True,
        null=True,
        on_delete=models.CASCADE)
    is_enable = models.BooleanField(_('enable'),
                                    default=False, blank=False, null=False)

    class Meta:
        ordering = ['-id']
        verbose_name = _('comment')
        verbose_name_plural = verbose_name
        get_latest_by = 'id'
        indexes = [
            # 优化评论列表查询：article + parent_comment + is_enable组合索引
            models.Index(fields=['article', 'parent_comment', 'is_enable'], name='idx_art_parent_enable'),
            # 优化侧边栏评论查询：is_enable + id组合索引
            models.Index(fields=['is_enable', '-id'], name='idx_enable_id'),
        ]

    def __str__(self):
        return self.body

    def get_reactions_summary(self, user=None):
        """
        获取评论的 reactions 统计信息
        返回格式: {
            '👍': {
                'count': 5,
                'has_reacted': True,
                'users': ['Alice', 'Bob', 'Charlie']
            },
            '❤️': {'count': 3, 'has_reacted': False, 'users': [...]},
            ...
        }
        """
        from django.db.models import Count

        reactions = CommentReaction.objects.filter(
            comment=self
        ).values('reaction_type').annotate(count=Count('id'))

        result = {}
        for reaction in reactions:
            emoji = reaction['reaction_type']

            # 获取该 emoji 的所有点赞用户
            reaction_users = CommentReaction.objects.filter(
                comment=self,
                reaction_type=emoji
            ).select_related('user')[:10]  # 最多显示10个用户

            user_names = [r.user.nickname or r.user.username for r in reaction_users]

            result[emoji] = {
                'count': reaction['count'],
                'has_reacted': False,
                'users': user_names
            }

            if user and user.is_authenticated:
                result[emoji]['has_reacted'] = CommentReaction.objects.filter(
                    comment=self,
                    user=user,
                    reaction_type=emoji
                ).exists()

        return result


class CommentReaction(models.Model):
    """
    评论的 Emoji 反应/点赞
    """
    REACTION_CHOICES = [
        ('👍', 'thumbs_up'),
        ('👎', 'thumbs_down'),
        ('❤️', 'heart'),
        ('😄', 'laugh'),
        ('🎉', 'hooray'),
        ('😕', 'confused'),
        ('🚀', 'rocket'),
        ('👀', 'eyes'),
    ]

    comment = models.ForeignKey(
        Comment,
        verbose_name=_('comment'),
        on_delete=models.CASCADE,
        related_name='reactions'
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('user'),
        on_delete=models.CASCADE
    )
    reaction_type = models.CharField(
        _('reaction type'),
        max_length=10,
        choices=REACTION_CHOICES
    )
    created_at = models.DateTimeField(_('created at'), auto_now_add=True)

    class Meta:
        verbose_name = _('comment reaction')
        verbose_name_plural = _('comment reactions')
        # 每个用户对同一评论的同一种 emoji 只能点一次
        unique_together = ['comment', 'user', 'reaction_type']
        indexes = [
            models.Index(fields=['comment', 'reaction_type'], name='idx_comment_reaction'),
        ]

    def __str__(self):
        return f'{self.user.username} - {self.reaction_type} on comment {self.comment.id}'

apps/comments/forms.py
from django import forms
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    parent_comment_id = forms.IntegerField(widget=forms.HiddenInput, required=False)

    class Meta:
        model = Comment
        fields = ['body']

apps/comments/views.py
# Create your views here.
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic.edit import FormView

from blog.models import Article
from .forms import CommentForm
from .models import Comment


class CommentPostView(FormView):
    form_class = CommentForm
    template_name = 'blog/article_detail.html'

    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        return super(CommentPostView, self).dispatch(*args, **kwargs)

    def get(self, request, *args, **kwargs):
        article_id = self.kwargs['article_id']
        article = get_object_or_404(Article, pk=article_id)
        url = article.get_absolute_url()
        return HttpResponseRedirect(url + "#comments")

    def form_invalid(self, form):
        article_id = self.kwargs['article_id']
        article = get_object_or_404(Article, pk=article_id)

        return self.render_to_response({'form': form, 'article': article})

    def form_valid(self, form):
        """提交的数据验证合法后的逻辑"""
        user = self.request.user

        article_id = self.kwargs['article_id']
        article = get_object_or_404(Article, pk=article_id)

        if article.comment_status == 'c' or article.status == 'c':
            raise ValidationError("该文章评论已关闭.")
        comment = form.save(False)
        comment.article = article

        comment.author = user

        if form.cleaned_data['parent_comment_id']:
            parent_comment = Comment.objects.get(
                pk=form.cleaned_data['parent_comment_id']
            )
            comment.parent_comment = parent_comment

        comment.save(True)
        return HttpResponseRedirect(
            "%s#div-comment-%d" % (article.get_absolute_url(), comment.pk)
        )

comments/views.py
# Create your views here.
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.views import View

from accounts.models import BlogUser
from blog.models import Article
from djangoblog.base_views import AuthenticatedFormView
from .forms import CommentForm
from .models import Comment, CommentReaction


class CommentPostView(AuthenticatedFormView):
    """
    评论提交视图

    使用 AuthenticatedFormView 基类，自动提供：
    - 登录验证（未登录用户会被重定向）
    - CSRF 保护
    """
    form_class = CommentForm
    template_name = 'blog/article_detail.html'

    def get(self, request, *args, **kwargs):
        article_id = self.kwargs['article_id']
        article = get_object_or_404(Article, pk=article_id)
        url = article.get_absolute_url()
        return HttpResponseRedirect(url + "#comments")

    def form_invalid(self, form):
        article_id = self.kwargs['article_id']
        article = get_object_or_404(Article, pk=article_id)

        return self.render_to_response({
            'form': form,
            'article': article
        })

    def form_valid(self, form):
        """提交的数据验证合法后的逻辑"""
        user = self.request.user
        author = BlogUser.objects.get(pk=user.pk)
        article_id = self.kwargs['article_id']
        article = get_object_or_404(Article, pk=article_id)

        if article.comment_status == 'c' or article.status == 'c':
            raise ValidationError("该文章评论已关闭.")
        comment = form.save(False)
        comment.article = article
        from djangoblog.utils import get_blog_setting
        settings = get_blog_setting()
        if not settings.comment_need_review:
            comment.is_enable = True
        comment.author = author

        if form.cleaned_data['parent_comment_id']:
            parent_comment = Comment.objects.get(
                pk=form.cleaned_data['parent_comment_id'])
            comment.parent_comment = parent_comment

        comment.save(True)
        return HttpResponseRedirect(
            "%s#div-comment-%d" %
            (article.get_absolute_url(), comment.pk))


class CommentReactionView(View):
    """
    评论 Emoji 反应 API
    GET /comment/<comment_id>/react - 获取 reactions（公开）
    POST /comment/<comment_id>/react - 切换 reaction（需要登录）
    """

    def get(self, request, comment_id):
        """获取评论的 reactions 数据（公开访问）"""
        comment = get_object_or_404(Comment, id=comment_id, is_enable=True)

        # 传递用户信息，如果未登录则传递 None
        user = request.user if request.user.is_authenticated else None
        reactions_data = comment.get_reactions_summary(user)

        return JsonResponse({
            'success': True,
            'reactions': reactions_data
        })

    def post(self, request, comment_id):
        # POST 需要登录验证
        if not request.user.is_authenticated:
            return JsonResponse({
                'success': False,
                'error': 'Authentication required'
            }, status=401)
        # 获取评论（只有已启用的评论才能点赞）
        comment = get_object_or_404(Comment, id=comment_id, is_enable=True)

        # 获取 reaction 类型
        reaction_type = request.POST.get('reaction_type')

        # 验证 reaction_type 是否合法
        valid_reactions = [choice[0] for choice in CommentReaction.REACTION_CHOICES]
        if reaction_type not in valid_reactions:
            return JsonResponse({
                'error': 'Invalid reaction type'
            }, status=400)

        # 切换 reaction（如果已存在则删除，否则创建）
        reaction, created = CommentReaction.objects.get_or_create(
            comment=comment,
            user=request.user,
            reaction_type=reaction_type
        )

        if not created:
            # 已存在，删除它（取消点赞）
            reaction.delete()
            action = 'removed'
        else:
            action = 'added'

        # 返回该评论的所有 reactions 统计
        reactions_data = comment.get_reactions_summary(request.user)

        return JsonResponse({
            'success': True,
            'action': action,
            'reactions': reactions_data
        })

templates/comments/tags/comment_item.html
{% load blog_tags %}
<li class="comment even thread-even depth-{{ depth }} parent" id="comment-{{ comment_item.pk }}">
    <div id="div-comment-{{ comment_item.pk }}" class="comment-body">
        <div class="comment-author vcard">
            <img alt="{{ comment_item.author.username }}的头像"
                 src="{{ comment_item.author.email|gravatar_url:150 }}"
                 srcset="{{ comment_item.author.email|gravatar_url:150 }}"
                 class="avatar avatar-96 photo"
                 loading="lazy"
                 decoding="async">
            <cite class="fn">
                <a rel="nofollow"
                        {% if comment_item.author.is_superuser %}
                   href="{{ comment_item.author.get_absolute_url }}"
                        {% else %}
                   href="#"
                        {% endif %}
                   rel="external nofollow"
                   class="url">{{ comment_item.author.username }}
                </a>
            </cite>

        </div>

        <div class="comment-meta commentmetadata">
            <div>{{ comment_item.creation_time }}</div>
            <div>回复给:@{{ comment_item.author.parent_comment.username }}</div>
        </div>
        <div class="entry-content">{{ comment_item.body|comment_markdown }}</div>
        <div class="reply"><a rel="nofollow" class="comment-reply-link"
                              href="javascript:void(0)"
                              onclick="do_reply({{ comment_item.pk }})"
                              aria-label="回复给{{ comment_item.author.username }}">回复</a></div>
    </div>

</li><!-- #comment-## -->

templates/comments/tags/comment_item_tree.html
{% load blog_tags %}
<li class="comment even thread-even depth-{{ depth }} parent" id="comment-{{ comment_item.pk }}"
    style="margin-left: {% widthratio depth 1 3 %}rem">
    <div id="div-comment-{{ comment_item.pk }}" class="comment-body">
        <div class="comment-author vcard">
            <img alt="{{ comment_item.author.username }}的头像"
                 src="{{ comment_item.author.email|gravatar_url:150 }}"
                 srcset="{{ comment_item.author.email|gravatar_url:150 }}"
                 class="avatar avatar-96 photo"
                 loading="lazy"
                 decoding="async">
            <cite class="fn">
                <a rel="nofollow"
                        {% if comment_item.author.is_superuser %}
                   href="{{ comment_item.author.get_absolute_url }}"
                        {% else %}
                   href="#"
                        {% endif %}
                   rel="external nofollow"
                   class="url">{{ comment_item.author.username }}
                </a>
            </cite>

        </div>

        <div class="comment-meta commentmetadata">
            {{ comment_item.creation_time }}
        </div>
        <p>
            {% if comment_item.parent_comment %}
                <div>回复 <a
                        href="#comment-{{ comment_item.parent_comment.pk }}">@{{ comment_item.parent_comment.author.username }}</a>
                </div>
            {% endif %}
        </p>

        <div class="entry-content">{{ comment_item.body|comment_markdown }}</div>

        <div class="reply"><a rel="nofollow" class="comment-reply-link"
                              href="javascript:void(0)" data-pk="{{ comment_item.pk }}"
                              aria-label="回复给{{ comment_item.author.username }}">回复</a></div>
    </div>

</li><!-- #comment-## -->
{% query article_comments parent_comment=comment_item as cc_comments %}
{% for cc in cc_comments %}
    {% with comment_item=cc template_name="comments/tags/comment_item_tree.html" %}
        {% if depth >= 1 %}
            {% include template_name %}
        {% else %}
            {% with depth=depth|add:1 %}
                {% include template_name %}
            {% endwith %}
        {% endif %}
    {% endwith %}
{% endfor %}

templates/comments/tags/comment_list.html
<dev>
    <section id="comments" class="themeform">
        {% load blog_tags %}
        {% load comments_tags %}
        {% load cache %}

        <ul class="comment-tabs group">
            <li class="active"><a href="#commentlist-container"><i
                    class="fa fa-comments-o"></i>评论<span>{{ comment_count }}</span></a></li>

        </ul>
        {% if article_comments %}
            <div id="commentlist-container" class="comment-tab block">
                <ol class="commentlist">
                    {#                    {% query article_comments parent_comment=None as parent_comments %}#}
                    {% for comment_item in p_comments %}

                        {% with 0 as depth %}
                            {% include "comments/tags/comment_item_tree.html" %}
                        {% endwith %}
                    {% endfor %}

                </ol><!--/.commentlist-->
                <div class="navigation">
                    <nav class="nav-single">
                        {% if comment_prev_page_url %}
                            <div class="nav-previous">
                        <span><a href="{{ comment_prev_page_url }}" rel="prev"><span
                                class="meta-nav">←</span> 上一页</a></span>
                            </div>
                        {% endif %}
                        {% if comment_next_page_url %}
                            <div class="nav-next">
                        <span><a href="{{ comment_next_page_url }}" rel="next">下一页 <span
                                class="meta-nav">→</span></a></span>
                            </div>
                        {% endif %}
                    </nav>
                </div>
                <br/>
            </div>
        {% endif %}
    </section>

</dev>

templates/comments/tags/post_comment.html
<div id="comments" class="comments-area">

    <div id="respond" class="comment-respond">
        <h3 id="reply-title" class="comment-reply-title">发表评论
            <small><a rel="nofollow" id="cancel-comment-reply-link" href="/wordpress/?p=3786#respond"
                      class="hidden">取消回复</a></small>
        </h3>
        <form action="{% url 'comments:postcomment' article.pk %}" method="post" id="commentform"
              class="comment-form">{% csrf_token %}
            <p class="comment-form-comment">
                {{ form.body.label_tag }}

                {{ form.body }}
                {{ form.body.errors }}
            </p>
            {{ form.parent_comment_id }}
            <div class="form-submit">
                {% if COMMENT_NEED_REVIEW %}
                    <span class="comment-markdown"> 支持markdown，评论经审核后才会显示。</span>
                {% else %}
                    <span class="comment-markdown"> 支持markdown。</span>
                {% endif %}
                <input name="submit" type="submit" id="submit" class="submit" value="发表评论"/>
                <small class="cancel-comment hidden" id="cancel_comment">
                    <a href="javascript:void(0)" id="cancel-comment-reply-link" onclick="cancel_reply()">取消回复</a>
                </small>
            </div>
        </form>
    </div><!-- #respond -->

</div><!-- #comments .comments-area -->

templates/comments/tags/post_comment_modern.html
<!-- 现代化发布评论表单 -->
<hr class="my-12 border-t-2 border-gray-300 dark:border-gray-600">
<div x-data="{ showForm: true }"
     id="respond"
     class="comment-respond">

    <!-- 表单标题 -->
    <h3 class="text-2xl font-bold mb-6 text-gray-900 dark:text-gray-100 flex items-center space-x-2">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/>
        </svg>
        <span>发表评论</span>
    </h3>

    <!-- 评论表单 -->
    <form action="{% url 'comments:postcomment' article.pk %}"
          method="post"
          id="commentform"
          class="comment-form space-y-4"
          hx-post="{% url 'comments:postcomment' article.pk %}"
          hx-target="#main"
          hx-select="#main"
          hx-swap="innerHTML"
          hx-push-url="true">

        {% csrf_token %}

        <!-- 评论内容 -->
        <div class="form-group">
            <label for="{{ form.body.id_for_label }}"
                   class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {{ form.body.label }}
                <span class="text-red-500">*</span>
            </label>

            <textarea
                name="{{ form.body.html_name }}"
                id="{{ form.body.id_for_label }}"
                class="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 resize-y transition-all"
                placeholder="写下你的评论... (支持Markdown语法)"
                rows="6"
                required
            >{{ form.body.value|default:'' }}</textarea>

            {% if form.body.errors %}
                <div class="mt-2 text-sm text-red-600 dark:text-red-400">
                    {{ form.body.errors }}
                </div>
            {% endif %}
        </div>

        <!-- 隐藏字段 -->
        {{ form.parent_comment_id }}

        <!-- Markdown提示和提交按钮 -->
        <div class="flex items-center justify-between flex-wrap gap-4">
            <div class="flex items-start space-x-2 text-sm text-gray-600 dark:text-gray-400">
                <svg class="w-5 h-5 flex-shrink-0 mt-0.5" fill="currentColor" viewBox="0 0 20 20">
                    <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"/>
                </svg>
                <div>
                    <div class="font-medium">支持Markdown语法</div>
                    {% if COMMENT_NEED_REVIEW %}
                        <div class="text-xs mt-0.5">评论经审核后才会显示</div>
                    {% endif %}
                </div>
            </div>

            <div class="flex space-x-3">
                <!-- 取消回复按钮（条件显示） -->
                <button type="button"
                        id="cancel_comment"
                        onclick="cancel_reply()"
                        class="hidden px-6 py-2.5 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors items-center space-x-2">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/>
                    </svg>
                    <span>取消回复</span>
                </button>

                <!-- 提交按钮 -->
                <button type="submit"
                        id="submit-comment-btn"
                        class="px-6 py-2.5 bg-primary-500 text-white rounded-lg hover:bg-primary-600 transition-all shadow-md hover:shadow-lg inline-flex items-center space-x-2 font-medium">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"/>
                    </svg>
                    <span>发表评论</span>
                </button>
            </div>
        </div>

        <!-- Markdown快速指南 -->
        <details class="mt-4 p-4 bg-gray-50 dark:bg-gray-900 rounded-lg border border-gray-200 dark:border-gray-700">
            <summary class="cursor-pointer text-sm font-medium text-gray-700 dark:text-gray-300 hover:text-primary-500 transition-colors">
                Markdown语法指南
            </summary>
            <div class="mt-3 text-sm text-gray-600 dark:text-gray-400 space-y-2">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
                    <div><code class="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">**粗体**</code></div>
                    <div><code class="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">*斜体*</code></div>
                    <div><code class="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">`代码`</code></div>
                    <div><code class="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">[链接](url)</code></div>
                    <div><code class="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">- 列表</code></div>
                    <div><code class="px-2 py-1 bg-gray-200 dark:bg-gray-800 rounded">> 引用</code></div>
                </div>
            </div>
        </details>
    </form>
</div>

<!-- 保留旧的JavaScript函数以兼容 -->
<script>
    // 这些函数由旧的jQuery代码使用，保留以确保兼容性
    function do_reply(parentid) {
        document.getElementById("id_parent_comment_id").value = parentid;
        const form = document.getElementById("commentform");
        const target = document.getElementById("div-comment-" + parentid);
        if (target && form) {
            target.appendChild(form);
        }
        const cancelBtn = document.getElementById("cancel_comment");
        if (cancelBtn) {
            cancelBtn.classList.remove("hidden");
            cancelBtn.classList.add("inline-flex");
        }
    }

    function cancel_reply() {
        document.getElementById("id_parent_comment_id").value = '';
        const form = document.getElementById("commentform");
        const respond = document.getElementById("respond");
        if (form && respond) {
            respond.appendChild(form);
        }
        const cancelBtn = document.getElementById("cancel_comment");
        if (cancelBtn) {
            cancelBtn.classList.add("hidden");
            cancelBtn.classList.remove("inline-flex");
        }
    }
</script>