accounts/urls.py
from django.urls import path
from django.urls import re_path

from . import views
from .forms import LoginForm

app_name = "accounts"

urlpatterns = [re_path(r'^login/$',
                       views.LoginView.as_view(success_url='/'),
                       name='login',
                       kwargs={'authentication_form': LoginForm}),
               re_path(r'^register/$',
                       views.RegisterView.as_view(success_url="/"),
                       name='register'),
               re_path(r'^logout/$',
                       views.LogoutView.as_view(),
                       name='logout'),
               path(r'account/result.html',
                    views.account_result,
                    name='result'),
               re_path(r'^forget_password/$',
                       views.ForgetPasswordView.as_view(),
                       name='forget_password'),
               re_path(r'^forget_password_code/$',
                       views.ForgetPasswordEmailCode.as_view(),
                       name='forget_password_code'),
               ]

apps/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = "blog"
urlpatterns = [
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'page/<int:page>/', views.IndexView.as_view(), name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid',
    ),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail',
    ),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page',
    ),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail',
    ),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page',
    ),
    path(r'tag/<slug:tag_name>.html', views.TagDetailView.as_view(), name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page',
    ),
    path(
        'archives.html',
        cache_page(60 * 60)(views.ArchivesView.as_view()),
        name='archives',
    ),
    path('links.html', views.LinkListView.as_view(), name='links'),
    path(r'upload', views.fileupload, name='upload'),
]

blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = "blog"
urlpatterns = [
    path(
        r'',
        views.IndexView.as_view(),
        name='index'),
    path(
        r'page/<int:page>/',
        views.IndexView.as_view(),
        name='index_page'),
    path(
        r'article/<int:year>/<int:month>/<int:day>/<int:article_id>.html',
        views.ArticleDetailView.as_view(),
        name='detailbyid'),
    path(
        r'category/<slug:category_name>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail'),
    path(
        r'category/<slug:category_name>/<int:page>.html',
        views.CategoryDetailView.as_view(),
        name='category_detail_page'),
    path(
        r'author/<author_name>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail'),
    path(
        r'author/<author_name>/<int:page>.html',
        views.AuthorDetailView.as_view(),
        name='author_detail_page'),
    path(
        r'tag/<slug:tag_name>.html',
        views.TagDetailView.as_view(),
        name='tag_detail'),
    path(
        r'tag/<slug:tag_name>/<int:page>.html',
        views.TagDetailView.as_view(),
        name='tag_detail_page'),
    path(
        'archives.html',
        cache_page(
            60 * 60)(
            views.ArchivesView.as_view()),
        name='archives'),
    path(
        'links.html',
        views.LinkListView.as_view(),
        name='links'),
    path(
        r'upload',
        views.fileupload,
        name='upload'),
    path(
        r'clean',
        views.clean_cache_view,
        name='clean'),
    path(
        r'compare-versions',
        views.compare_versions,
        name='compare_versions'),
]

djangoblog/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.urls import re_path
from haystack.views import search_view_factory
from django.http import JsonResponse
import time

from blog.views import EsSearchView
from djangoblog.admin_site import admin_site
from djangoblog.elasticsearch_backend import ElasticSearchModelSearchForm
from djangoblog.feeds import DjangoBlogFeed
from djangoblog.sitemap import ArticleSiteMap, CategorySiteMap, StaticViewSitemap, TagSiteMap, UserSiteMap

sitemaps = {

    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'


def health_check(request):
    """
    健康检查接口
    简单返回服务健康状态
    """
    return JsonResponse({
        'status': 'healthy',
        'timestamp': time.time()
    })

from servermanager.views import statistics_view

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('health/', health_check, name='health_check'),
    path('statistics/', statistics_view, name='statistics'),
    path('servermanager/', include('servermanager.urls', namespace='servermanager')),
]
urlpatterns += i18n_patterns(
    re_path(r'^admin/', admin_site.urls),
    re_path(r'mdeditor/', include('mdeditor.urls')),
    re_path(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
    re_path(r'^feed/$', DjangoBlogFeed()),
    re_path(r'^rss/$', DjangoBlogFeed()),
    re_path('^search', search_view_factory(view_class=EsSearchView, form_class=ElasticSearchModelSearchForm),
            name='search'),
    path('servermanager/', include('servermanager.urls', namespace='servermanager')),
    re_path(r'', include('owntracks.urls', namespace='owntracks')),
    re_path(r'', include('blog.urls', namespace='blog')),
    re_path(r'', include('comments.urls', namespace='comment')),
    re_path(r'', include('accounts.urls', namespace='account')),
    re_path(r'', include('oauth.urls', namespace='oauth'))
    , prefix_default_language=False) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

apps/blog/models.py
import logging
from abc import abstractmethod

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from mdeditor.fields import MDTextField
from uuslug import slugify

from djangoblog.utils import cache_decorator, cache
from djangoblog.utils import get_current_site

logger = logging.getLogger(__name__)


class LinkShowType(models.TextChoices):
    I = ('i', '首页')
    L = ('l', '列表页')
    P = ('p', '文章页面')
    A = ('a', '全站')
    S = ('s', '友情链接页面')


class BaseModel(models.Model):
    id = models.AutoField(primary_key=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    def save(self, *args, **kwargs):
        is_update_views = (
            isinstance(self, Article)
            and 'update_fields' in kwargs
            and kwargs['update_fields'] == ['views']
        )
        if is_update_views:
            Article.objects.filter(pk=self.pk).update(views=self.views)
        else:
            if 'slug' in self.__dict__:
                slug = (
                    getattr(self, 'title')
                    if 'title' in self.__dict__
                    else getattr(self, 'name')
                )
                setattr(self, 'slug', slugify(slug))
            super().save(*args, **kwargs)

    def get_full_url(self):
        site = get_current_site().domain
        url = "https://{site}{path}".format(site=site, path=self.get_absolute_url())
        return url

    class Meta:
        abstract = True

    @abstractmethod
    def get_absolute_url(self):
        pass


class Article(BaseModel):
    """文章"""

    STATUS_CHOICES = (
        ('d', '草稿'),
        ('p', '发表'),
    )
    COMMENT_STATUS = (
        ('o', '打开'),
        ('c', '关闭'),
    )
    TYPE = (
        ('a', '文章'),
        ('p', '页面'),
    )
    title = models.CharField('标题', max_length=200, unique=True)
    body = MDTextField('正文')
    pub_time = models.DateTimeField('发布时间', blank=False, null=False, default=now)
    status = models.CharField('文章状态', max_length=1, choices=STATUS_CHOICES, default='p')
    comment_status = models.CharField(
        '评论状态', max_length=1, choices=COMMENT_STATUS, default='o'
    )
    type = models.CharField('类型', max_length=1, choices=TYPE, default='a')
    views = models.PositiveIntegerField('浏览量', default=0)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='作者',
        blank=False,
        null=False,
        on_delete=models.CASCADE,
    )
    article_order = models.IntegerField(
        '排序,数字越大越靠前', blank=False, null=False, default=0
    )
    show_toc = models.BooleanField("是否显示toc目录", blank=False, null=False, default=False)
    category = models.ForeignKey(
        'Category', verbose_name='分类', on_delete=models.CASCADE, blank=False, null=False
    )
    tags = models.ManyToManyField('Tag', verbose_name='标签集合', blank=True)

    def body_to_string(self):
        return self.body

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-article_order', '-pub_time']
        verbose_name = "文章"
        verbose_name_plural = verbose_name
        get_latest_by = 'id'

    def get_absolute_url(self):
        return reverse(
            'blog:detailbyid',
            kwargs={
                'article_id': self.id,
                'year': self.created_time.year,
                'month': self.created_time.month,
                'day': self.created_time.day,
            },
        )

    @cache_decorator(60 * 60 * 10)
    def get_category_tree(self):
        tree = self.category.get_category_tree()
        names = list(map(lambda c: (c.name, c.get_absolute_url()), tree))

        return names

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

    def viewed(self):
        self.views += 1
        self.save(update_fields=['views'])

    def comment_list(self):
        cache_key = 'article_comments_{id}'.format(id=self.id)
        value = cache.get(cache_key)
        if value:
            logger.info('get article comments:{id}'.format(id=self.id))
            return value
        else:
            comments = self.comment_set.filter(is_enable=True).order_by('-id')
            cache.set(cache_key, comments, 60 * 100)
            logger.info('set article comments:{id}'.format(id=self.id))
            return comments

    def get_admin_url(self):
        info = (self._meta.app_label, self._meta.model_name)
        return reverse('admin:%s_%s_change' % info, args=(self.pk,))

    @cache_decorator(expiration=60 * 100)
    def next_article(self):
        # 下一篇
        return Article.objects.filter(id__gt=self.id, status='p').order_by('id').first()

    @cache_decorator(expiration=60 * 100)
    def prev_article(self):
        # 前一篇
        return Article.objects.filter(id__lt=self.id, status='p').first()


class Category(BaseModel):
    """文章分类"""

    name = models.CharField('分类名', max_length=30, unique=True)
    parent_category = models.ForeignKey(
        'self', verbose_name="父级分类", blank=True, null=True, on_delete=models.CASCADE
    )
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)
    index = models.IntegerField(default=0, verbose_name="权重排序-越大越靠前")

    class Meta:
        ordering = ['-index']
        verbose_name = "分类"
        verbose_name_plural = verbose_name

    def get_absolute_url(self):
        return reverse('blog:category_detail', kwargs={'category_name': self.slug})

    def __str__(self):
        return self.name

    @cache_decorator(60 * 60 * 10)
    def get_category_tree(self):
        """
        递归获得分类目录的父级
        :return:
        """
        categorys = []

        def parse(category):
            categorys.append(category)
            if category.parent_category:
                parse(category.parent_category)

        parse(self)
        return categorys

    @cache_decorator(60 * 60 * 10)
    def get_sub_categorys(self):
        """
        获得当前分类目录所有子集
        :return:
        """
        categorys = []
        all_categorys = Category.objects.all()

        def parse(category):
            if category not in categorys:
                categorys.append(category)
            childs = all_categorys.filter(parent_category=category)
            for child in childs:
                if category not in categorys:
                    categorys.append(child)
                parse(child)

        parse(self)
        return categorys


class Tag(BaseModel):
    """文章标签"""

    name = models.CharField('标签名', max_length=30, unique=True)
    slug = models.SlugField(default='no-slug', max_length=60, blank=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:tag_detail', kwargs={'tag_name': self.slug})

    @cache_decorator(60 * 60 * 10)
    def get_article_count(self):
        return Article.objects.filter(tags__name=self.name).distinct().count()

    class Meta:
        ordering = ['name']
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Links(models.Model):
    """友情链接"""

    name = models.CharField('链接名称', max_length=30, unique=True)
    link = models.URLField('链接地址')
    sequence = models.IntegerField('排序', unique=True)
    is_enable = models.BooleanField('是否显示', default=True, blank=False, null=False)
    show_type = models.CharField(
        '显示类型', max_length=1, choices=LinkShowType.choices, default=LinkShowType.I
    )
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    class Meta:
        ordering = ['sequence']
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class SideBar(models.Model):
    """侧边栏,可以展示一些html内容"""

    name = models.CharField('标题', max_length=100)
    content = models.TextField("内容")
    sequence = models.IntegerField('排序', unique=True)
    is_enable = models.BooleanField('是否启用', default=True)
    created_time = models.DateTimeField('创建时间', default=now)
    last_mod_time = models.DateTimeField('修改时间', default=now)

    class Meta:
        ordering = ['sequence']
        verbose_name = '侧边栏'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class BlogSettings(models.Model):
    """blog的配置"""

    sitename = models.CharField(
        "网站名称", max_length=200, null=False, blank=False, default=''
    )
    site_description = models.TextField(
        "网站描述", max_length=1000, null=False, blank=False, default=''
    )
    site_seo_description = models.TextField(
        "网站SEO描述", max_length=1000, null=False, blank=False, default=''
    )
    site_keywords = models.TextField(
        "网站关键字", max_length=1000, null=False, blank=False, default=''
    )
    article_sub_length = models.IntegerField("文章摘要长度", default=300)
    sidebar_article_count = models.IntegerField("侧边栏文章数目", default=10)
    sidebar_comment_count = models.IntegerField("侧边栏评论数目", default=5)
    article_comment_count = models.IntegerField("文章页面默认显示评论数目", default=5)
    show_google_adsense = models.BooleanField('是否显示谷歌广告', default=False)
    google_adsense_codes = models.TextField(
        '广告内容', max_length=2000, null=True, blank=True, default=''
    )
    open_site_comment = models.BooleanField('是否打开网站评论功能', default=True)
    global_header = models.TextField("公共头部", null=True, blank=True, default='')
    global_footer = models.TextField("公共尾部", null=True, blank=True, default='')
    beiancode = models.CharField(
        '备案号', max_length=2000, null=True, blank=True, default=''
    )
    analyticscode = models.TextField(
        "网站统计代码", max_length=1000, null=False, blank=False, default=''
    )

apps/blog/forms.py
import logging

from django import forms
from haystack.forms import SearchForm

logger = logging.getLogger(__name__)


class BlogSearchForm(SearchForm):
    querydata = forms.CharField(required=True)

    def search(self):
        datas = super(BlogSearchForm, self).search()
        if not self.is_valid():
            return self.no_query_found()

        if self.cleaned_data['querydata']:
            logger.info(self.cleaned_data['querydata'])
        return datas

templates/blog/article_archives.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load cache %}
{% load i18n %}
{% block header %}

    <title>{% trans 'article archive' %} | {{ SITE_NAME }}</title>

    <meta name="description" content="浏览所有文章的时间归档，按年份和月份整理。"/>
    <meta name="keywords" content="文章归档, {{ SITE_KEYWORDS }}"/>
    <link rel="canonical" href="{{ request.scheme }}://{{ request.get_host }}{{ request.path }}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="{% trans 'article archive' %} | {{ SITE_NAME }}"/>
    <meta property="og:description" content="浏览所有文章的时间归档"/>
    <meta property="og:url" content="{{ request.get_full_path }}"/>
    <meta property="og:site_name" content="{{ SITE_NAME }}"/>

{% endblock %}
{% block content %}
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8 items-start">
        <!-- 主内容区域 -->
        <div id="primary" class="site-content lg:col-span-8">
            <div id="content" role="main">

            <!-- 面包屑导航 -->
            <nav aria-label="breadcrumb" class="breadcrumb-nav">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/" class="breadcrumb-link">
                            <svg class="breadcrumb-icon" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"/>
                            </svg>
                            {% trans 'Home' %}
                        </a>
                    </li>
                    <li class="breadcrumb-separator" aria-hidden="true">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                        </svg>
                    </li>
                    <li class="breadcrumb-item">
                        <span class="breadcrumb-current">{% trans 'article archive' %}</span>
                    </li>
                </ol>
            </nav>

            <!-- 归档页面头部 -->
            <header class="archive-header-modern">
                <div class="archive-hero">
                    <div class="archive-icon">
                        <svg class="w-16 h-16" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"/>
                        </svg>
                    </div>
                    <h1 class="archive-title-modern">{% trans 'article archive' %}</h1>
                    <p class="archive-subtitle">共 {{ article_list|length }} 篇文章</p>
                </div>
            </header>

            <!-- 归档时间线 -->
            <div class="archive-timeline">
                {% regroup article_list by pub_time.year as year_post_group %}

                {% for year in year_post_group %}
                    <div class="timeline-year-block">
                        <!-- 年份标签 -->
                        <div class="timeline-year-badge">
                            <span class="year-number">{{ year.grouper }}</span>
                            <span class="year-count">{{ year.list|length }} 篇</span>
                        </div>

                        {% regroup year.list by pub_time.month as month_post_group %}

                        {% for month in month_post_group %}
                            <div class="timeline-month-block">
                                <!-- 月份标签 -->
                                <div class="timeline-month-header">
                                    <div class="timeline-dot"></div>
                                    <h3 class="month-title">{{ month.grouper }}月</h3>
                                    <span class="month-count">{{ month.list|length }} 篇</span>
                                </div>

                                <!-- 文章列表 -->
                                <ul class="timeline-articles">
                                    {% for article in month.list %}
                                        <li class="timeline-article-item">
                                            <a href="{{ article.get_absolute_url }}" class="article-link group">
                                                <div class="article-info">
                                                    <span class="article-date">{{ article.pub_time|date:"m-d" }}</span>
                                                    <h4 class="article-title">{{ article.title }}</h4>
                                                </div>
                                                <div class="article-meta">
                                                    {% if article.category %}
                                                        <span class="article-category">
                                                            <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"/>
                                                            </svg>
                                                            {{ article.category.name }}
                                                        </span>
                                                    {% endif %}
                                                    <span class="article-views">
                                                        <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/>
                                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/>
                                                        </svg>
                                                        {{ article.views }}
                                                    </span>
                                                </div>
                                                <svg class="article-arrow" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                                                </svg>
                                            </a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>

            </div><!-- #content -->
        </div><!-- #primary -->

        <!-- 侧边栏 - 移动端(<1024px)自动堆叠到主内容下方 -->
        <aside id="secondary" class="widget-area lg:col-span-4">
            {% load_sidebar user 'i' %}
        </aside>
    </div>
{% endblock %}

templates/blog/article_detail.html
{% extends 'share_layout/base.html' %}
{% load blog_tags %}
{% load i18n %}

{% block header %}
    <!-- 基础SEO标签（由视图层提供） -->
    <title>{{ seo_title|default:SITE_NAME }}</title>
    <meta name="description" content="{{ seo_description|default:SITE_DESCRIPTION }}"/>
    <meta name="keywords" content="{{ seo_keywords|default:SITE_KEYWORDS }}"/>
    <link rel="canonical" href="{{ article.get_full_url }}"/>
{% endblock %}
{% block content %}
    <div class="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8 items-start">
        <!-- 主内容区域 - 调整为9列，给文章更多空间 -->
        <div id="primary" class="site-content lg:col-span-8">
            <!-- 移除max-w-3xl限制，使用更宽的max-w-5xl，让文章内容更舒展 -->
            <!-- 移动端不加padding，避免多层嵌套导致内容过窄 -->
            <div id="content" role="main" class="max-w-5xl mx-auto px-0 sm:px-4">

            {% load_article_detail article False user %}

            {% if article.type == 'a' %}
                <nav class="nav-single">
                    <h3 class="assistive-text">文章导航</h3>
                    {% if next_article %}

                        <span class="nav-previous"><a href="{{ next_article.get_absolute_url }}" rel="prev"><span
                                class="meta-nav">&larr;</span> {{ next_article.title }}</a></span>
                    {% endif %}
                    {% if prev_article %}
                        <span class="nav-next"><a href="{{ prev_article.get_absolute_url }}"
                                                  rel="next">{{ prev_article.title }} <span
                                class="meta-nav">&rarr;</span></a></span>
                    {% endif %}
                </nav><!-- .nav-single -->
            {% endif %}

            </div><!-- #content -->

            {% if article.comment_status == "o" and OPEN_SITE_COMMENT %}

            {# 使用现代化评论系统 #}
            {% include 'comments/tags/comment_list_modern.html' %}

            {% if user.is_authenticated %}
                {% include 'comments/tags/post_comment_modern.html' %}
            {% else %}
                <hr class="my-12 border-t-2 border-gray-300 dark:border-gray-600">
                <div class="comments-area p-6 bg-gradient-to-r from-primary-50 to-blue-50 dark:from-gray-800 dark:to-gray-900 rounded-lg border border-primary-200 dark:border-gray-700">
                    <div class="flex items-start space-x-4">
                        <svg class="w-8 h-8 text-primary-500 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"/>
                        </svg>
                        <div>
                            <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">
                                登录后发表评论
                            </h3>
                            <p class="text-gray-700 dark:text-gray-300 mb-4">
                                您还没有登录，请先
                                <a href="{% url "account:login" %}?next={{ request.get_full_path }}"
                                   class="text-primary-600 dark:text-primary-400 font-medium hover:underline"
                                   rel="nofollow"
                                   hx-boost="false">登录</a>
                                后发表评论。
                            </p>

                            {% load oauth_tags %}
                            <div class="flex flex-wrap gap-2">
                                {% load_oauth_applications request %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
            {% endif %}
        </div><!-- #primary -->

        <!-- 侧边栏 - 移动端(<1024px)自动堆叠到主内容下方 -->
        <!-- 侧边栏 - 调整为3列，更紧凑 -->
        <aside id="secondary" class="widget-area lg:col-span-4">
            {% load_sidebar user "p" %}
        </aside>
    </div>
{% endblock %}

templates/blog/categorytree.html
<ol class="breadcrumb">
    {% for name,url in names %}
        <li>
            <a href="{{ url }}">
                {{ name }}
            </a>
        </li>
    {% endfor %}
</ol>